// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0p_qnACAMJHbOY3bhl1zBmcfAX3J9xos',
    appId: '1:812708651904:android:64ce4eb2bc3d9321bad765',
    messagingSenderId: '812708651904',
    projectId: 'vokabelquiz-3de5f',
    storageBucket: 'vokabelquiz-3de5f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3yzaUekWS1-FY3vFnBHlAoYjA_3b7_g',
    appId: '1:812708651904:web:88c2bc2e59d040d8bad765',
    messagingSenderId: '812708651904',
    projectId: 'vokabelquiz-3de5f',
    authDomain: 'vokabelquiz-3de5f.firebaseapp.com',
    storageBucket: 'vokabelquiz-3de5f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGuPJF3Y1LHyc5KUaX8WlE9uLG4q3v7uY',
    appId: '1:812708651904:ios:760e0018999fa2c2bad765',
    messagingSenderId: '812708651904',
    projectId: 'vokabelquiz-3de5f',
    storageBucket: 'vokabelquiz-3de5f.firebasestorage.app',
    iosBundleId: 'de.frankrollmann.flutterTest01',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGuPJF3Y1LHyc5KUaX8WlE9uLG4q3v7uY',
    appId: '1:812708651904:ios:1f51c44577010f6cbad765',
    messagingSenderId: '812708651904',
    projectId: 'vokabelquiz-3de5f',
    storageBucket: 'vokabelquiz-3de5f.firebasestorage.app',
    iosBundleId: 'de.frankrollmann..flutterTest01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM3yzaUekWS1-FY3vFnBHlAoYjA_3b7_g',
    appId: '1:812708651904:web:005fc624b79b28dfbad765',
    messagingSenderId: '812708651904',
    projectId: 'vokabelquiz-3de5f',
    authDomain: 'vokabelquiz-3de5f.firebaseapp.com',
    storageBucket: 'vokabelquiz-3de5f.firebasestorage.app',
  );

}